#!/bin/bash
if [ -n "$1" ]; then
   str="$*";
   x-terminal-emulator -e google-chrome --incognito "https://www.google.com/search?q=$str";
else
   x-terminal-emulator -e google-chrome --incognito 
fi

